codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: 40%
        threshold: 2%
    patch: off
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header,diff"
  behavior: default
  require_changes: no
