name: Go
on:
  push:
    branches:
      - main
  pull_request:

env:
  CC: clang
  CXX: clang++
jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        go-version: [ "1.19" ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: build
      run: |
        make build
  test:
    name: test
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        go-version: [ "1.19" ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: test
      run: go test -v ./... -count=1
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      - name: measure coverage
        run: |
          make cover
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      - name: run linter
        run: |
          make lint
